### ISSUE TITLE
are you looking for contributions?

### ISSUE THREAD

**Issue by willofdaedalus** [PurinPintakhiew/go-convert-units#1]
like the title asks; are you looking for contributions or is this a personal learning project?
I'd like to contribute where possible

**Comment by PurinPintakhiew** [comment]
This is a project created for learning purposes. You are welcome to use the code and build upon it. 😸

**Comment by PurinPintakhiew** [comment]
If you have any suggestions or issues to report, feel free to leave them here. 😺

**Comment by willofdaedalus** [comment]
okay then
my suggestions would be to put your convertunits into a seperate directory in the root so that you can simplify your project structure
then also maybe do a `map[string]func(string) float64` so that in your ConvertTemperature you can just return that value
that's aside though so don't stress if you don't want to go that way
I'll close this issue for now though
good luck on your project and don't forget to have fun

**Comment by PurinPintakhiew** [comment]
thank you for the suggestion. i will make improvements and adjustments accordingly. 😸
